// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TopGHRepos.Data;

namespace TopGHRepos.Data.Migrations
{
    [DbContext(typeof(TopGHReposContext))]
    partial class TopGHReposContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("TopGHRepos.Models.Entities.RepositoryInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CloneUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBranch")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Fork")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ForksCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<long>("GitHubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasDownloads")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasIssues")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPages")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasWiki")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Homepage")
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseApiUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("MirrorUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OpenIssuesCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerLoginName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Private")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("PushedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SshUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("StargazersCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SvnUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WatchersCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.ToTable("RepositoryInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
