name: Build Executables

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
    paths-ignore: 
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore: 
      - '**.md'

jobs: 
  build_exec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os: [win-x64, linux-x64, osx-x64]
        configuration: [Release]
        project: [TopGHRepos.CMD]
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
        
    - name: Publish ${{ matrix.os }} ${{ matrix.configuration }} - dotnet publish 
      working-directory: src/${{ matrix.project }}
      run: |
        dotnet publish -c ${{ matrix.configuration }} \
        -r ${{ matrix.os }} \
        --self-contained \
        -p:PublishSingleFile=true \
        -p:DebugType=None \
        -p:IncludeNativeLibrariesForSelfExtract=true

      #Ignore pdb files
    - name: Pack ${{ matrix.os }} - Zip
      working-directory: src/${{ matrix.project }}/bin/${{ matrix.configuration }}/net8.0/${{ matrix.os }}/publish/
      run: zip -r ${{ matrix.project }}.zip .

    - name: Upload ${{ matrix.os }} - Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.project }}-${{ matrix.os }}.zip
        path: src/${{ matrix.project }}/bin/${{ matrix.configuration }}/net8.0/${{ matrix.os }}/publish/${{ matrix.project }}.zip
